version: "3.9"
services:
  threejs:
    build: .
    command: /bin/sh -c "pnpm install && pnpm run start --host"
    volumes:
      - .:/threejs
    ports:
      - "3000:3000"
      - "5173:5173"
    tty: true

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db

  threejs-go-api:
    image:
      threejs_go_api_threejs-go-api:latest
    container_name: threejs-go-api
    ports:
      - "8081:8080"
    depends_on:
      - mongodb

volumes:
  mongo_data: